FROM node:22-alpine as build

WORKDIR /frontend
# Install dependencies first (for better caching)
COPY package.json ./
RUN npm install
# Copy application code
COPY . .
# Set the args from docker-compose
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

# Build the app
RUN npm run build

FROM nginx:alpine AS production

# Copy your app
COPY --from=build /frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]