FROM node:22-alpine

WORKDIR /frontend

# Install dependencies first (for better caching)
COPY package.json ./
# Change the line below if different architecture or platform
RUN npm install

# Copy application code
COPY . .

# Start development server with hot reloading
CMD ["npm", "run", "dev"]
