version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    args:
        - VITE_API_URL=http://localhost:8000/api
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL="http://localhost:8000/api"
    depends_on:
      - backend
    networks:
      - app_network
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5220"
      - "8001:7080"
    volumes:
      - ./backend:/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_SECRET_KEY=YOUR_SECRET_KEY
      - ConnectionStrings__DefaultConnection=Host=app-db;Database=YOUR_DB_NAME;Username=YOUR_USERNAME;Password=YOUR_PASSWORD
    depends_on:
      - app-db
    networks:
      - app_network
    restart: always

  app-db:
    image: postgres:13
    restart: always
    volumes: 
        - db-vol:/var/lib/postgresql/data
        - ../schemas/graduate_better_postgres_init.sql:/docker-entrypoint-initdb.d/graduate_better_postgres_init.sql
    environment:
        - POSTGRES_DB=YOUR_DB_NAME
        - POSTGRES_USER=YOUR_USERNAME
        - POSTGRES_PASSWORD=YOUR_PASSWORD
        - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
        - "5432:5432"
    networks:
      - app_network
      - shared_network

volumes:
  db-vol:

networks:
  app_network:
    driver: bridge
  shared_network:
    driver: bridge
    external: true
    name: shared_network